// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Foot.tsx";
import * as $$1 from "./islands/Logo.tsx";
import * as $$2 from "./islands/Moon.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Foot.tsx": $$0,
    "./islands/Logo.tsx": $$1,
    "./islands/Moon.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
